
name: .NET Core Desktop

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest
    name: Dotnet Build
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.*'
      - run: dotnet publish -c Release --runtime win-x64
      - run: powershell curl https://github.com/aiqinxuancai/discord-proxy/releases/download/v0.0.8/Release.zip -o Release.zip
      - run: powershell Expand-Archive -Path .\Release.zip -DestinationPath .\Release
      - run: powershell New-Item -ItemType Directory -Force -Path ".\build\Data"
      - run: powershell Copy-Item -Path ".\Release\version.dll" -Destination ".\build\Data"

      - run: powershell Copy-Item -Path "$env:GITHUB_WORKSPACE\DiscordProxyStart\bin\Release\net7.0\win-x64\publish\DiscordProxyStart.exe" -Destination ".\build"
      - run: powershell Copy-Item -Path "$env:GITHUB_WORKSPACE\DiscordProxyStart\bin\Release\net7.0\win-x64\publish\DiscordProxyStart.pdb" -Destination ".\build"
      - run: powershell Copy-Item -Path "$env:GITHUB_WORKSPACE\DiscordProxyStart\bin\Release\net7.0\win-x64\publish\Config.ini" -Destination ".\build"
      #- run: powershell Compress-Archive -Path "$env:GITHUB_WORKSPACE\DiscordProxyStart\bin\Release\net7.0\win-x64\publish\DiscordProxyStart.exe", ".\Release\version.dll"  -DestinationPath .\DiscordProxyStart.zip

      - run: powershell Compress-Archive -Path ".\build" -DestinationPath ".\DiscordProxyStart-win-amd64.zip"
      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "DiscordProxyStart-win-amd64.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

        
